### ISSUE TITLE
Emulation of Included Files functionality for GM4HTML5

### ISSUE THREAD

**Issue by cher-nov** [cher-nov/gm8_compat#2]
https://docs.microsoft.com/en-us/windows/win32/menurc/introduction-to-resources
https://docs.microsoft.com/en-us/windows/win32/menurc/resource-compiler
https://docs.microsoft.com/en-us/windows/win32/cmpapi/-compression-portal
https://docs.microsoft.com/en-us/windows/win32/api/_cmpapi/

Or just disable somehow the unpacking of these files into the working directory on engine startup (byte-patching the engine on `DLL_PROCESS_ATTACH`).

**Comment by omicronrex** [comment]
Turns out this is just an IDE limitation - using a 218 runner in 141 enables the use of all included file options.

**Comment by cher-nov** [comment]
Oh, thank you very much.
